### ISSUE TITLE
When running -o option with -i option

### ISSUE THREAD

**Issue by ycechungAI** [Kevan-Y/text-ssg#4]
found an issue when running a new output folder name with input

for instance
ssg -i '.\samples\Sherlock Holmes Selected Stories\Silver Blaze.txt' -o test

will output

Error: Directory must exist.

**Comment by Kevan-Y** [comment]
Base on the instruction:
```
allow the user to specify a different output directory using --output or -o. If not specified, dist will be used, but if the user specifies a different output path, use that. Print an error if the specified output path is not a valid directory.
```
The directory must valid which mean must exist

**Comment by ycechungAI** [comment]
alright ill close the issue
