### ISSUE TITLE
Break index.js up for readability

### ISSUE THREAD

**Issue by humphd** [Kevan-Y/text-ssg#8]
The code at https://github.com/Kevan-Y/text-ssg/blob/master/src/index.js#L54-L92 should be its own function, ideally in a separate file.  When you see yourself indenting that far to the right, it's often a good indication that you should consider breaking things up into separate functions, files, etc.

It will help your code to be more maintainable if you leave the arg parsing in `main.js`, and push the logic for things like file handling, HTML generation, etc. into separate files.

**Comment by Kevan-Y** [comment]
Changed putting all checks in a folder and export to index.js
